networks:
  laravel:
    driver: bridge
    
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Iff_ecommercetest
    restart: unless-stopped
    tty: true
    expose:
      - "9000"
    volumes:
      - ${PROJECT_PATH}:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    environment: []  # Variabili rimosse
    networks:
      - laravel

  nginx:
    image: nginx:latest
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./docker-configs/nginx/app.conf:/etc/nginx/conf.d/default.conf
      - ${PROJECT_PATH}:/var/www/html
    depends_on:
      - web
    networks:
      - laravel

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: iff_ecommercetest_db
      MYSQL_USER: iff_ecommercetest_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    networks:
      - laravel